INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Sunless Sea", "video game", 20000, "July 1", "September 30");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Undertale", "video game", 8000, "November 15", "December 31");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Pillars of Eternity", "video game", 50000, "March 1", "June 11");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Funky dice", "merchandise", 5000, "May 1", "May 30");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Squid plushies", "merchandise", 10000, "June 1", "August 31");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("my lunch", "service", 10, "July 1", "July 2");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Sunless Skies", "video game", 20000, "October 1", "December 1");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("twitch shoutout", "service", 20, "September 29", "September 30");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("idk man what else was crowdfunded", "merchandise", 1000, "July 12", "July 22");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("just one mooooore", "service", 500, "February 1", "February 28");
INSERT INTO users (name, age) VALUES ("Anna", 25);
INSERT INTO users (name, age) VALUES ("Dagon", 4);
INSERT INTO users (name, age) VALUES ("Kerry", 50);
INSERT INTO users (name, age) VALUES ("Shannon", 51);
INSERT INTO users (name, age) VALUES ("Jon", 3);
INSERT INTO users (name, age) VALUES ("Cricket", 2);
INSERT INTO users (name, age) VALUES ("Max", 4);
INSERT INTO users (name, age) VALUES ("Eleanor", 2);
INSERT INTO users (name, age) VALUES ("Brigid", 2);
INSERT INTO users (name, age) VALUES ("Chester", 10);
INSERT INTO users (name, age) VALUES ("Pogo", 11);
INSERT INTO users (name, age) VALUES ("Sami", 9);
INSERT INTO users (name, age) VALUES ("Jim", 73);
INSERT INTO users (name, age) VALUES ("Judy", 65);
INSERT INTO users (name, age) VALUES ("Kelly", 46);
INSERT INTO users (name, age) VALUES ("Alex", 18);
INSERT INTO users (name, age) VALUES ("Katie", 22);
INSERT INTO users (name, age) VALUES ("Brian", 25);
INSERT INTO users (name, age) VALUES ("Claire", 23);
INSERT INTO users (name, age) VALUES ("im out of relatives and pets", 33);
INSERT INTO pledges (user_id, project_id, amount) VALUES (11, 7, 700);
INSERT INTO pledges (user_id, project_id, amount) VALUES (5, 3, 100);
INSERT INTO pledges (user_id, project_id, amount) VALUES (17, 2, 10);
INSERT INTO pledges (user_id, project_id, amount) VALUES (20, 8, 50);
INSERT INTO pledges (user_id, project_id, amount) VALUES (2, 1, 25);
INSERT INTO pledges (user_id, project_id, amount) VALUES (1, 10, 70);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4, 4, 30);
INSERT INTO pledges (user_id, project_id, amount) VALUES (5, 2, 150);
INSERT INTO pledges (user_id, project_id, amount) VALUES (19, 7, 40);
INSERT INTO pledges (user_id, project_id, amount) VALUES (16, 6, 80);
INSERT INTO pledges (user_id, project_id, amount) VALUES (14, 4, 25);
INSERT INTO pledges (user_id, project_id, amount) VALUES (17, 3, 15);
INSERT INTO pledges (user_id, project_id, amount) VALUES (8, 8, 20);
INSERT INTO pledges (user_id, project_id, amount) VALUES (7, 5, 75);
INSERT INTO pledges (user_id, project_id, amount) VALUES (5, 9, 10);
INSERT INTO pledges (user_id, project_id, amount) VALUES (9, 1, 50);
INSERT INTO pledges (user_id, project_id, amount) VALUES (2, 1, 70);
INSERT INTO pledges (user_id, project_id, amount) VALUES (1, 8, 20);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4, 3, 10);
INSERT INTO pledges (user_id, project_id, amount) VALUES (19, 1, 50);
INSERT INTO pledges (user_id, project_id, amount) VALUES (10, 10, 100);
INSERT INTO pledges (user_id, project_id, amount) VALUES (15, 2, 50);
INSERT INTO pledges (user_id, project_id, amount) VALUES (12, 7, 25);
INSERT INTO pledges (user_id, project_id, amount) VALUES (14, 8, 30);
INSERT INTO pledges (user_id, project_id, amount) VALUES (4, 2, 50);
INSERT INTO pledges (user_id, project_id, amount) VALUES (2, 6, 10);
INSERT INTO pledges (user_id, project_id, amount) VALUES (1, 2, 20);
INSERT INTO pledges (user_id, project_id, amount) VALUES (6, 8, 150);
INSERT INTO pledges (user_id, project_id, amount) VALUES (12, 7, 20);
INSERT INTO pledges (user_id, project_id, amount) VALUES (11, 1, 25);

